homebrew_apps:
    - git
    - brew-cask

homebrew_taps:
  - caskroom/cask
  - homebrew/binary
  - homebrew/dupes
  - homebrew/php
  - homebrew/versions
  - caskroom/versions

cask_apps: []

alfred_cask_integration: true